name: Translate Content

on:
  push:
    paths:
      - 'content/it/**'
      - '.github/workflows/translate.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deep-translator pyyaml

      - name: Run translation script
        run: python translate_md.py
